version: "2"

run:
  timeout: 5m
  build-tags:
    - integration
    - e2e

linters:
  default: none
  enable:
    - errcheck
    - govet
    - staticcheck
    - wsl_v5

formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/solidDoWant/tape-archiver
