package report_test

import (
	"bytes"
	"io"
	"strings"
	"testing"
	"time"

	"github.com/ledongthuc/pdf"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"

	"github.com/solidDoWant/tape-archiver/pkg/report"
)

// completeManifest returns a manifest exercising every SPEC §9 field.
func completeManifest() report.Manifest {
	return report.Manifest{
		RunID: "run-2026-06-29T00-00-00Z-abc123",
		Date:  time.Date(2026, time.June, 29, 12, 30, 0, 0, time.UTC),
		Archives: []report.Archive{
			{
				Name:            "k8s-group-photos",
				MemberVolumes:   []string{"pvc-photos-raw", "pvc-photos-thumbs"},
				SourceSnapshots: []string{"bulk-pool-01/photos@snap-20260629"},
				Files: []report.ArchiveFile{
					{
						Name:   "photos.tar.zst.age.000",
						Size:   1073741824,
						SHA256: "9f86d081884c7d659a2feaa0c55ad015a3bf4f1b2b0b822cd15d6c15b0f00a08",
					},
					{
						Name:   "photos.tar.zst.age.par2",
						Size:   107374182,
						SHA256: "60303ae22b998861bce3b28f33eec1be758a213c86c93c076dbe9f558c11c752",
					},
				},
			},
			{
				Name:            "zfs-media",
				MemberVolumes:   []string{"bulk-pool-01/media"},
				SourceSnapshots: []string{"bulk-pool-01/media@snap-20260629"},
				Files: []report.ArchiveFile{
					{
						Name:   "media.tar.age.000",
						Size:   5368709120,
						SHA256: "2c26b46b68ffc68ff99b453c1d30413413422d706483bfa0f98a5e886266e7ae",
					},
				},
			},
		},
		Tapes: []report.Tape{
			{
				Barcode:  "TAPE0001L8",
				Contents: []string{"k8s-group-photos", "zfs-media"},
				WriteHealth: &report.WriteHealth{
					ThroughputMBps: 152.5,
					FloorMBps:      50,
					FloorKnown:     true,
					BelowFloor:     false,
					Repositions:    0,
					Healthy:        true,
				},
			},
			{
				Barcode:  "TAPE0002L8",
				Contents: []string{"k8s-group-photos", "zfs-media"},
				WriteHealth: &report.WriteHealth{
					ThroughputMBps: 41.3,
					FloorMBps:      50,
					FloorKnown:     true,
					BelowFloor:     true,
					Repositions:    7,
					TapeAlertFlags: []string{"8: Cleaning required"},
					Healthy:        false,
				},
			},
		},
		Build: report.BuildParams{
			ToolVersion:     "tape-archiver v1.2.3",
			AgeVersion:      "age 1.3.1",
			Par2Version:     "par2cmdline-turbo 1.1.0",
			LTFSVersion:     "ltfs 2.5.0",
			SliceSize:       268435456,
			PAR2Redundancy:  "fill-to-capacity",
			DriveModel:      "IBM ULT3580-HH8",
			DriveGeneration: "LTO-8 (reads LTO-7/8; LTO-9 also reads LTO-8)",
			DriveSerial:     "10WT0A1B2C",
			LibraryModel:    "Quantum Scalar i3",
		},
		AgeIdentity:       "AGE-SECRET-KEY-PQ-1QQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQ9XYZ42",
		RecoveryProcedure: "1. Load any one tape into a compatible LTO-8 drive.\n2. Mount the LTFS volume read-only.\n3. Verify each slice against its SHA-256 checksum; repair with par2 if needed.\n4. Concatenate slices, decrypt with the age identity above, and unpack the tar.",
	}
}

// extractText renders m to a PDF, parses it back with a pure-Go reader, and
// returns the extracted plain text. It asserts the PDF is structurally valid.
func extractText(t *testing.T, m report.Manifest) string {
	t.Helper()

	var buf bytes.Buffer
	require.NoError(t, report.Build(m, &buf))
	require.NotZero(t, buf.Len(), "Build produced an empty PDF")

	reader, err := pdf.NewReader(bytes.NewReader(buf.Bytes()), int64(buf.Len()))
	require.NoError(t, err, "generated bytes are not a valid PDF")
	require.GreaterOrEqual(t, reader.NumPage(), 1)

	textReader, err := reader.GetPlainText()
	require.NoError(t, err)

	text, err := io.ReadAll(textReader)
	require.NoError(t, err)

	return string(text)
}

// stripWhitespace removes all whitespace so substring checks test the rendered
// content independent of how the extractor spaces or wraps glyphs.
func stripWhitespace(s string) string {
	return strings.Join(strings.Fields(s), "")
}

func TestBuildContainsEverySpec9Field(t *testing.T) {
	t.Parallel()

	manifest := completeManifest()
	extracted := stripWhitespace(extractText(t, manifest))

	tests := []struct {
		name  string
		value string
	}{
		{name: "run id", value: manifest.RunID},
		{name: "date", value: manifest.Date.Format(time.RFC3339)},
		{name: "archive name (group)", value: "k8s-group-photos"},
		{name: "archive name (zfs)", value: "zfs-media"},
		{name: "member volume", value: "pvc-photos-thumbs"},
		{name: "source snapshot", value: "bulk-pool-01/media@snap-20260629"},
		{name: "file name", value: "photos.tar.zst.age.000"},
		{name: "file size", value: "1,073,741,824"},
		{name: "archive checksum 1", value: manifest.Archives[0].Files[0].SHA256},
		{name: "archive checksum 2", value: manifest.Archives[0].Files[1].SHA256},
		{name: "archive checksum 3", value: manifest.Archives[1].Files[0].SHA256},
		{name: "tape barcode 1", value: "TAPE0001L8"},
		{name: "tape barcode 2", value: "TAPE0002L8"},
		{name: "tool version", value: "tape-archiver v1.2.3"},
		{name: "age version", value: "age 1.3.1"},
		{name: "par2 version", value: "par2cmdline-turbo 1.1.0"},
		{name: "ltfs version", value: "ltfs 2.5.0"},
		{name: "slice size", value: "268,435,456"},
		{name: "par2 redundancy", value: "fill-to-capacity"},
		{name: "drive model", value: "IBM ULT3580-HH8"},
		{name: "drive generation", value: "reads LTO-7/8"},
		{name: "drive serial", value: "10WT0A1B2C"},
		{name: "library model", value: "Quantum Scalar i3"},
		{name: "age private identity", value: manifest.AgeIdentity},
		{name: "recovery procedure", value: "decrypt with the age identity above"},
		{name: "write-health throughput", value: "152.5"},
		{name: "write-health floor", value: "50"},
		{name: "write-health healthy status", value: "healthy"},
		{name: "write-health below-floor status", value: "below floor"},
		{name: "write-health reposition count", value: "7"},
		{name: "write-health TapeAlert flag", value: "Cleaning required"},
	}

	for _, test := range tests {
		t.Run(test.name, func(t *testing.T) {
			t.Parallel()
			assert.Contains(t, extracted, stripWhitespace(test.value),
				"extracted PDF text is missing the %s field", test.name)
		})
	}
}

// TestBuildWriteHealthSection asserts the report renders each write-health state
// distinctly (SPEC §14): healthy, below-floor, repositions, TapeAlert, and the
// "not measured" fallback when a tape carries no measurement.
func TestBuildWriteHealthSection(t *testing.T) {
	t.Parallel()

	manifest := func(health *report.WriteHealth) report.Manifest {
		m := completeManifest()
		m.Tapes = []report.Tape{{Barcode: "TAPE9999L6", Contents: []string{"zfs-media"}, WriteHealth: health}}

		return m
	}

	tests := []struct {
		name     string
		health   *report.WriteHealth
		contains []string
	}{
		{
			name:     "healthy",
			health:   &report.WriteHealth{ThroughputMBps: 160.0, FloorMBps: 50, FloorKnown: true, Healthy: true},
			contains: []string{"160.0", "healthy"},
		},
		{
			name:     "below floor",
			health:   &report.WriteHealth{ThroughputMBps: 42.0, FloorMBps: 50, FloorKnown: true, BelowFloor: true},
			contains: []string{"42.0", "below floor"},
		},
		{
			name:     "repositions",
			health:   &report.WriteHealth{ThroughputMBps: 120.0, FloorMBps: 50, FloorKnown: true, Repositions: 12},
			contains: []string{"12 repositions"},
		},
		{
			name:     "tape alert",
			health:   &report.WriteHealth{ThroughputMBps: 120.0, FloorMBps: 50, FloorKnown: true, TapeAlertFlags: []string{"20: Clean now"}},
			contains: []string{"TapeAlert", "Clean now"},
		},
		{
			name:     "floor unknown",
			health:   &report.WriteHealth{ThroughputMBps: 90.0, FloorKnown: false},
			contains: []string{"90.0", "floor unknown"},
		},
		{
			name:     "not measured",
			health:   nil,
			contains: []string{"not measured"},
		},
	}

	for _, test := range tests {
		t.Run(test.name, func(t *testing.T) {
			t.Parallel()

			extracted := stripWhitespace(extractText(t, manifest(test.health)))

			for _, want := range test.contains {
				assert.Contains(t, extracted, stripWhitespace(want),
					"write-health %q state should render %q", test.name, want)
			}
		})
	}
}

func TestBuildProducesValidPDF(t *testing.T) {
	t.Parallel()

	var buf bytes.Buffer
	require.NoError(t, report.Build(completeManifest(), &buf))

	assert.True(t, bytes.HasPrefix(buf.Bytes(), []byte("%PDF-")),
		"output does not start with the PDF magic header")
}
