---
apiVersion: v2
name: tape-archiver-web
description: Helm chart for the tape-archiver web UI (browser SPA + JSON API HTTP server)
type: application
version: 0.0.1-dev
appVersion: 0.0.1-dev
dependencies:
  - name: common
    repository: https://bjw-s-labs.github.io/helm-charts
    version: 5.0.1
