// Package schemas embeds the committed run-config JSON Schema
// (run-config.schema.json, generated by cmd/gen-config-schema — see
// docs/configuration.md) so it can be served at runtime by pkg/runsapi's
// GET /api/config/schema, byte-for-byte identical to the file checked into
// this directory. This is the only Go consumer of the schema file; the
// embed directive must live in this directory because it can only reach
// its own directory subtree.
//
// Embedding the committed file (rather than hand-duplicating its constraints
// in the web UI) means the config page's client-side validation can never
// silently drift from the schema `make generate-schema` produces from
// internal/config's own types — the two are read from the same bytes.
package schemas

import _ "embed"

//go:embed run-config.schema.json
var runConfigSchemaJSON []byte

// RunConfigSchema returns the committed run-config JSON Schema document,
// exactly as checked into schemas/run-config.schema.json.
func RunConfigSchema() []byte {
	return runConfigSchemaJSON
}
