// Package agewrap wraps the bundled age binary to encrypt streams to
// post-quantum recipients (SPEC §7).
package agewrap

import (
	"context"
	"errors"
	"fmt"
	"io"
	"os/exec"
	"strings"
)

// pqRecipientPrefix is the prefix of an age native post-quantum recipient
// (HPKE with hybrid ML-KEM-768), generated by `age-keygen -pq`. SPEC §7 mandates
// post-quantum recipients only — an X25519-only `age1…` recipient is rejected.
const pqRecipientPrefix = "age1pq1"

// ErrNonPostQuantumRecipient is returned when Encrypt is called with no
// recipients, or with a recipient that is not an age post-quantum recipient
// (one beginning with "age1pq1"). It is reported before the age binary is
// invoked, so no plaintext is ever fed to a non-post-quantum recipient.
var ErrNonPostQuantumRecipient = errors.New("recipient is not an age post-quantum recipient (age1pq1…)")

// Encrypt reads from src and writes an age-encrypted stream to dst, encrypted to
// each of recipients. It shells out to the bundled age binary — the exact tool
// whose binary and source ship on the recovery disc (SPEC §7, §10) — so the
// bytes written are produced by the same implementation a future recoverer uses
// to decrypt them.
//
// Every recipient must be an age native post-quantum recipient (one beginning
// with "age1pq1"); at least one is required. If any recipient is missing or not
// post-quantum, Encrypt returns an error wrapping ErrNonPostQuantumRecipient
// without invoking age.
func Encrypt(ctx context.Context, dst io.Writer, src io.Reader, recipients ...string) error {
	if len(recipients) == 0 {
		return fmt.Errorf("%w: no recipients given", ErrNonPostQuantumRecipient)
	}

	// -e encrypts; -r repeats the recipient. Validate every recipient before
	// invoking age so plaintext is never handed to a non-post-quantum recipient.
	args := []string{"-e"}

	for _, recipient := range recipients {
		if !strings.HasPrefix(recipient, pqRecipientPrefix) {
			return fmt.Errorf("%w: %q", ErrNonPostQuantumRecipient, recipient)
		}

		args = append(args, "-r", recipient)
	}

	cmd := exec.CommandContext(ctx, "age", args...)
	cmd.Stdin = src
	cmd.Stdout = dst

	var stderr strings.Builder

	cmd.Stderr = &stderr

	if err := cmd.Run(); err != nil {
		if msg := strings.TrimSpace(stderr.String()); msg != "" {
			return fmt.Errorf("%s: %w: %s", cmd, err, msg)
		}

		return fmt.Errorf("%s: %w", cmd, err)
	}

	return nil
}
